stages:
  - docker

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  CI_REGISTRY: registry.nguyenanh-est.com
  CI_REGISTRY_URL: https://registry.nguyenanh-est.com
  IMAGE_NAME: "$CI_REGISTRY/$CI_PROJECT_PATH"

docker-build-and-push:
  stage: docker
  image: docker:latest
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "deploy" && $CI_MERGE_REQUEST_STATE == "merged"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "deploy" && $CI_PIPELINE_SOURCE == "push"'
      when: on_success
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - |
      TAG_LATEST="latest"
      TAG_BRANCH="$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID"

      echo "Building Docker image with tags:"
      echo " - $IMAGE_NAME:$TAG_LATEST"
      echo " - $IMAGE_NAME:$TAG_BRANCH"

      docker build --pull --rm \
        -t $IMAGE_NAME:$TAG_LATEST \
        -t $IMAGE_NAME:$TAG_BRANCH .

      echo "Pushing Docker images..."
      docker push $IMAGE_NAME:$TAG_LATEST
      docker push $IMAGE_NAME:$TAG_BRANCH

      echo "Cleaning up Docker images..."
      docker rmi $IMAGE_NAME:$TAG_LATEST $IMAGE_NAME:$TAG_BRANCH || true
      docker image prune -f --filter "dangling=true"
